alias ls='ls -G'
alias gp='git push'
alias gph='git push heroku master'
alias gcm='git commit -m' #git shortcut
alias gst='git status'
alias gd='git diff'
alias gaa='git add -A'
alias be='bundle exec'
alias ..='cd ..'
